services:
  db:
    image: mysql:5.7.26
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./api:/$WORKDIR
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    command: sh -c 'rm -f tmp/pids/server.pid && bundle && rails s -b 0.0.0.0'

volumes:
  mysql-data:
    driver: local