services:
  db:
    image: postgres:12.3-alpine
    environment:
      TZ: JST
      PGTZ: JST
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./api:/$WORKDIR
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    command: sh -c 'rm -f tmp/pids/server.pid && bundle && rails s -b 0.0.0.0'
